// Auto-generated by scripts/gen-castles-seo.mjs — do not edit
export const castlesSeo = {
  "hive": [
    {
      "name": "Chorus Conductor",
      "description": "All friendly creatures gain +10 Attack in battle. +50% Lucky Strike Damage, including from hero spells. This city’s dwellings produce +100% units."
    },
    {
      "name": "Tavern",
      "description": "Allows the hiring of new heroes."
    },
    {
      "name": "Marketplace",
      "description": "Allows resources to be traded."
    },
    {
      "name": "Apiary's Heart",
      "description": "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap."
    },
    {
      "name": "Apiary's Heart II",
      "description": "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade."
    },
    {
      "name": "Apiary's Heart III",
      "description": "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade."
    },
    {
      "name": "Resource Depot",
      "description": "Produces 1 Crystal daily."
    },
    {
      "name": "Alchemic Depot",
      "description": "Produces 5 Alchemical Dust daily."
    },
    {
      "name": "Beelzebub's Hand",
      "description": "Grants +2 Attack to any visiting hero."
    },
    {
      "name": "Bank",
      "description": "Produces 1000 Gold daily."
    },
    {
      "name": "Treasury",
      "description": "Produces 2000 Gold daily."
    },
    {
      "name": "Fortifications",
      "description": "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade."
    },
    {
      "name": "Fortifications II",
      "description": "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units."
    },
    {
      "name": "Fortifications III",
      "description": "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units."
    },
    {
      "name": "Paper nest",
      "description": "Allows the recruitment of Hornets."
    },
    {
      "name": "Paper nest II",
      "description": "Allows the recruitment of Chanters and Stingers."
    },
    {
      "name": "Sacrarium Rediti",
      "description": "Allows to revert a hero to level one once. The hero receives a permanent bonus to their attributes that depends on their level at the moment of the ritual."
    },
    {
      "name": "Carrion Lair",
      "description": "Allows the recruitment of Locusts."
    },
    {
      "name": "Carrion Lair II",
      "description": "Allows the recruitment of Overgrown Locusts and Harvester Locusts."
    },
    {
      "name": "Burning Soul Burrows",
      "description": "Allows the recruitment of Waurmos."
    },
    {
      "name": "Tower of Love",
      "description": "Allows the recruitment of Hive Queens."
    },
    {
      "name": "Tower of Love II",
      "description": "Allows the recruitment of Hive Mothers and Hive Huntresses."
    },
    {
      "name": "Neglected Housing",
      "description": "Allows the recruitment of Parasites."
    },
    {
      "name": "Neglected Housing II",
      "description": "Allows the recruitment of Warden Parasites and Ravager Parasites."
    },
    {
      "name": "Chitinous Ziggurat II",
      "description": "Allows the recruitment of Volcanic Scorpions and Spelaean Scorpions."
    },
    {
      "name": "Burning Soul Burrows II",
      "description": "Allows the recruitment of Devourers and Pyroboroses."
    },
    {
      "name": "Chitinous Ziggurat",
      "description": "Allows the recruitment of Scorpions."
    },
    {
      "name": "Apex",
      "description": "Allows the recruitment of Reavers."
    },
    {
      "name": "Apex II",
      "description": "Allows the recruitment of Menacing Reavers and Maniacal Reavers."
    },
    {
      "name": "Mage Guild",
      "description": "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild II",
      "description": "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild III",
      "description": "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild IV",
      "description": "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild V",
      "description": "Unlocks 3 random tier‑5 spells in the Magic Observatory and the ability to spend dust to upgrade tier-5 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–5 spells are added to their Spellbook."
    }
  ],
  "necropolis": [
    {
      "name": "Everserpent",
      "description": "All friendly creatures gain +10 Defense and take –50% Lucky Strike Damage in battle (including from spells). This city’s dwellings produce +100% units."
    },
    {
      "name": "Tavern",
      "description": "Allows the hiring of new heroes."
    },
    {
      "name": "Marketplace",
      "description": "Allows resources to be traded."
    },
    {
      "name": "Eternal Visage",
      "description": "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap."
    },
    {
      "name": "Eternal Visage II",
      "description": "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade."
    },
    {
      "name": "Eternal Visage III",
      "description": "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade."
    },
    {
      "name": "Resource Depot",
      "description": "Produces 1 Mercury daily."
    },
    {
      "name": "Alchemic Depot",
      "description": "Produces 5 Alchemical Dust daily."
    },
    {
      "name": "Bank",
      "description": "Produces 1000 Gold daily."
    },
    {
      "name": "Treasury",
      "description": "Produces 2000 Gold daily."
    },
    {
      "name": "Fortifications",
      "description": "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade."
    },
    {
      "name": "Fortifications II",
      "description": "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units."
    },
    {
      "name": "Fortifications III",
      "description": "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units."
    },
    {
      "name": "Undead Transformer",
      "description": "Allows sacrificing of any creatures to turn them into Undead units of the same tier."
    },
    {
      "name": "Kennel",
      "description": "Allows the recruitment of Undead Pets."
    },
    {
      "name": "Tomb of the Warriors",
      "description": "Allows the recruitment of Dread Knights."
    },
    {
      "name": "Tomb of the Warriors II",
      "description": "Allows the recruitment of Avatars of War and Hollow Reapers."
    },
    {
      "name": "Crypts and Graves",
      "description": "Allows the recruitment of Skeletons."
    },
    {
      "name": "Crypts and Graves II",
      "description": "Allows the recruitment of Skeleton Warriors and Skeleton Archers."
    },
    {
      "name": "Kennel II",
      "description": "Allows the recruitment of Barghests and Armored Hounds."
    },
    {
      "name": "Timeless Mansion II",
      "description": "Allows the recruitment of Pestilent Liches and Sanguine Liches."
    },
    {
      "name": "Bone Exchange",
      "description": "Allows the recruitment of Graverobbers."
    },
    {
      "name": "Timeless Mansion",
      "description": "Allows the recruitment of Liches."
    },
    {
      "name": "Chateau of Feasts",
      "description": "Allows the recruitment of Vampires."
    },
    {
      "name": "Chateau of Feasts II",
      "description": "Allows the recruitment of Vampire Lords and Vampire Scholars."
    },
    {
      "name": "Quiet Pavilion",
      "description": "Allows the recruitment of Wights."
    },
    {
      "name": "Quiet Pavilion II",
      "description": "Allows the recruitment of Wraiths and Phantasms."
    },
    {
      "name": "Bone Exchange II",
      "description": "Allows the recruitment of Merchants of Death and Kennelmasters."
    },
    {
      "name": "Well of Souls",
      "description": "Well of Souls"
    },
    {
      "name": "Mage Guild",
      "description": "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild II",
      "description": "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild III",
      "description": "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild IV",
      "description": "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild V",
      "description": "Unlocks 3 random tier‑5 spells in the Magic Observatory and the ability to spend dust to upgrade tier-5 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–5 spells are added to their Spellbook."
    }
  ],
  "grove": [
    {
      "name": "Spring of Life",
      "description": "+1 to all creature growth in all your cities. This city’s dwellings produce +100% units."
    },
    {
      "name": "Tavern",
      "description": "Allows the hiring of new heroes."
    },
    {
      "name": "Marketplace",
      "description": "Allows resources to be traded."
    },
    {
      "name": "Artifact Merchant",
      "description": "Allows artifacts to be traded."
    },
    {
      "name": "Grove Place",
      "description": "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap."
    },
    {
      "name": "Grove Place II",
      "description": "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade."
    },
    {
      "name": "Grove Place III",
      "description": "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade."
    },
    {
      "name": "Resource Depot",
      "description": "Produces 1 Crystal daily."
    },
    {
      "name": "Alchemic Depot",
      "description": "Produces 5 Alchemical Dust daily."
    },
    {
      "name": "Mother Nature",
      "description": "Grants +2 Spell Power to any visiting hero."
    },
    {
      "name": "Bank",
      "description": "Produces 1000 Gold daily."
    },
    {
      "name": "Treasury",
      "description": "Produces 2000 Gold daily."
    },
    {
      "name": "Mycelium Roots",
      "description": "Allows a hero to travel to any city of their choice under your control."
    },
    {
      "name": "Fortifications",
      "description": "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade."
    },
    {
      "name": "Fortifications II",
      "description": "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units."
    },
    {
      "name": "Fortifications III",
      "description": "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units."
    },
    {
      "name": "Faun Huts II",
      "description": "Allows the recruitment of Faun Archers and Faun Warriors."
    },
    {
      "name": "Hop Patch II",
      "description": "Allows the recruitment of Dawn Hoplets and Dusk Hoplets."
    },
    {
      "name": "Faun Huts",
      "description": "Allows the recruitment of Fauns."
    },
    {
      "name": "Hop Patch",
      "description": "Allows the recruitment of Hoplets."
    },
    {
      "name": "Shroomwood Shack",
      "description": "Allows the recruitment of Herbomancers."
    },
    {
      "name": "Shroomwood Shack II",
      "description": "Allows the recruitment of Sporemancers and Murmurmancers"
    },
    {
      "name": "Menhir Circle",
      "description": "Allows the recruitment of Vine Iriyads."
    },
    {
      "name": "Menhir Circle II",
      "description": "Allows the recruitment of Fungal Iriyads and Crystal Iriyads."
    },
    {
      "name": "Thunder Lair",
      "description": "Allows the recruitment of Qilins."
    },
    {
      "name": "Thunder Lair II",
      "description": "Allows the recruitment of Thunder Qilins and Mist Qilins."
    },
    {
      "name": "Blooming Pond",
      "description": "Allows the recruitment of Naiads."
    },
    {
      "name": "Blooming Pond II",
      "description": "Allows the recruitment of Vernal Naiads and Brumal Naiads."
    },
    {
      "name": "Pyre",
      "description": "Allows the recruitment of Phoenixes."
    },
    {
      "name": "Pyre II",
      "description": "Allows the recruitment of Flaming Phoenixes and Energy Phoenixes."
    },
    {
      "name": "Mage Guild",
      "description": "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild II",
      "description": "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild III",
      "description": "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild IV",
      "description": "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild V",
      "description": "Unlocks 3 random tier‑5 spells in the Magic Observatory and the ability to spend dust to upgrade tier-5 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–5 spells are added to their Spellbook."
    }
  ],
  "dungeon": [
    {
      "name": "Spy Network",
      "description": "Completely removes the fog of war. This city’s dwellings produce +100% units."
    },
    {
      "name": "Tavern",
      "description": "Allows the hiring of new heroes."
    },
    {
      "name": "Marketplace",
      "description": "Allows resources to be traded."
    },
    {
      "name": "Artifact Merchant",
      "description": "Allows artifacts to be traded."
    },
    {
      "name": "Byzantine Place",
      "description": "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap."
    },
    {
      "name": "Byzantine Place II",
      "description": "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade."
    },
    {
      "name": "Byzantine Place III",
      "description": "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade."
    },
    {
      "name": "Resource Depot",
      "description": "Produces 1 Gem daily."
    },
    {
      "name": "Alchemic Depot",
      "description": "Produces 5 Alchemical Dust daily."
    },
    {
      "name": "Gymnasium",
      "description": "Levels up any visiting hero once."
    },
    {
      "name": "Lyceum",
      "description": "Allows enchanting of magic scrolls so that they grant spells of maximum level."
    },
    {
      "name": "Bank",
      "description": "Produces 1000 Gold daily."
    },
    {
      "name": "Treasury",
      "description": "Produces 2000 Gold daily."
    },
    {
      "name": "Fortifications",
      "description": "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade."
    },
    {
      "name": "Fortifications II",
      "description": "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units."
    },
    {
      "name": "Fortifications III",
      "description": "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units."
    },
    {
      "name": "Warren",
      "description": "Allows the recruitment of Troglodytes."
    },
    {
      "name": "Warren II",
      "description": "Allows the recruitment of Infernal Troglodytes and Toxic Troglodytes."
    },
    {
      "name": "Amphitheater II",
      "description": "Allows the recruitment of Jasper Dancers and Aureate Dancers."
    },
    {
      "name": "Amphitheater",
      "description": "Allows the recruitment of Onyx Dancers."
    },
    {
      "name": "Stilled Voices",
      "description": "Allows the recruitment of Medusae."
    },
    {
      "name": "Stilled Voices II",
      "description": "Allows the recruitment of Medusa Sculptors and Medusa Queens."
    },
    {
      "name": "Safe House",
      "description": "Building details"
    },
    {
      "name": "Safe House II",
      "description": "Building details"
    },
    {
      "name": "Labyrinth II",
      "description": "Allows the recruitment of Minotaur Lords and Minotaur Vanguards."
    },
    {
      "name": "Chthonic Home",
      "description": "Allows the recruitment of Hydras."
    },
    {
      "name": "Chthonic Home II",
      "description": "Allows the recruitment of Chthonic Hydras and Infernal Hydras."
    },
    {
      "name": "Labyrinth",
      "description": "Allows the recruitment of Minotaurs."
    },
    {
      "name": "Cave Place",
      "description": "Allows the recruitment of Cave Dragons."
    },
    {
      "name": "Cave Place II",
      "description": "Allows the recruitment of Black Dragons and Ashen Dragons."
    },
    {
      "name": "Mage Guild",
      "description": "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild II",
      "description": "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild III",
      "description": "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild IV",
      "description": "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild V",
      "description": "Unlocks 3 random tier‑5 spells in the Magic Observatory and the ability to spend dust to upgrade tier-5 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–5 spells are added to their Spellbook."
    }
  ],
  "temple": [
    {
      "name": "Golden Calf",
      "description": "The owner's cities produce 1000 Gold and 1 of each other resource daily. This city's dwellings produce +100% units."
    },
    {
      "name": "Tavern",
      "description": "Allows the hiring of new heroes."
    },
    {
      "name": "Marketplace",
      "description": "Allows resources to be traded."
    },
    {
      "name": "Artifact Merchant",
      "description": "Allows artifacts to be traded."
    },
    {
      "name": "Solar Temple",
      "description": "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap."
    },
    {
      "name": "Solar Temple II",
      "description": "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade."
    },
    {
      "name": "Solar Temple III",
      "description": "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade."
    },
    {
      "name": "Resource Depot",
      "description": "Produces 1 Gem daily."
    },
    {
      "name": "Alchemic Depot",
      "description": "Produces 5 Alchemical Dust daily."
    },
    {
      "name": "Guild of Six Winds",
      "description": "Allows a selected hero to spend a day learning. They will be unavailable until the next day and receive a permanent increase to an attribute of their choice."
    },
    {
      "name": "Bank",
      "description": "Produces 1000 Gold daily."
    },
    {
      "name": "Treasury",
      "description": "Produces 2000 Gold daily."
    },
    {
      "name": "Scouting Skyship",
      "description": "Removes the fog of war within 20 squares around the city."
    },
    {
      "name": "Fortifications",
      "description": "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade."
    },
    {
      "name": "Fortifications II",
      "description": "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units."
    },
    {
      "name": "Fortifications III",
      "description": "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units."
    },
    {
      "name": "Garrison II",
      "description": "Allows the recruitment of Guard Captains and Sun’s Aegises."
    },
    {
      "name": "Hippodrome II",
      "description": "Allows the recruitment of Noble Cavalry and Sunspear Cavalry."
    },
    {
      "name": "Garrison",
      "description": "Allows the recruitment of Swordsmen."
    },
    {
      "name": "Hippodrome",
      "description": "Allows the recruitment of Cavalry."
    },
    {
      "name": "Threshold Basilica",
      "description": "Allows the recruitment of Inquisitors."
    },
    {
      "name": "Threshold Basilica II",
      "description": "Allows the recruitment of Mothers Superior and Excommunicators."
    },
    {
      "name": "Mews",
      "description": "Allows the recruitment of Crossbowmen."
    },
    {
      "name": "Griffin Rookery",
      "description": "Allows the recruitment of Griffins."
    },
    {
      "name": "Sundrop Chapel",
      "description": "Allows the recruitment of Lightweavers."
    },
    {
      "name": "Sundrop Chapel II",
      "description": "Allows the recruitment of Hierophants and Sun Heralds."
    },
    {
      "name": "Mews II",
      "description": "Allows the recruitment of Austringers and Marksmen."
    },
    {
      "name": "Griffin Rookery II",
      "description": "Allows the recruitment of Temple Griffins and Guardian Griffins."
    },
    {
      "name": "Radiant Forge",
      "description": "Allows the recruitment of Angels."
    },
    {
      "name": "Radiant Forge II",
      "description": "Allows the recruitment of Archangels and Apotheoses."
    },
    {
      "name": "Mage Guild",
      "description": "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild II",
      "description": "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild III",
      "description": "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild IV",
      "description": "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook."
    }
  ],
  "schism": [
    {
      "name": "Firmament's Abyss",
      "description": "Building a Mage Guild in this city unlocks all spells of the corresponding tier. This city’s dwellings produce +100% units."
    },
    {
      "name": "Tavern",
      "description": "Allows the hiring of new heroes."
    },
    {
      "name": "Marketplace",
      "description": "Allows resources to be traded."
    },
    {
      "name": "Artifact Merchant",
      "description": "Allows artifacts to be traded."
    },
    {
      "name": "Abyssal Remnant",
      "description": "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap."
    },
    {
      "name": "Abyssal Remnant II",
      "description": "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade."
    },
    {
      "name": "Abyssal Remnant III",
      "description": "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade."
    },
    {
      "name": "Resource Depot",
      "description": "Produces 1 Gem daily."
    },
    {
      "name": "Alchemic Depot",
      "description": "Produces 5 Alchemical Dust daily."
    },
    {
      "name": "Great Library",
      "description": "Grants +2 Knowledge to any visiting hero."
    },
    {
      "name": "Bank",
      "description": "Produces 1000 Gold daily."
    },
    {
      "name": "Treasury",
      "description": "Produces 2000 Gold daily."
    },
    {
      "name": "Fortifications",
      "description": "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade."
    },
    {
      "name": "Fortifications II",
      "description": "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units."
    },
    {
      "name": "Fortifications III",
      "description": "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units."
    },
    {
      "name": "Cultist Spire",
      "description": "Allows the recruitment of Cultists."
    },
    {
      "name": "Cultist Spire II",
      "description": "Allows the recruitment of Binders and Votaries."
    },
    {
      "name": "House of Chains",
      "description": "Allows the recruitment of Concubi."
    },
    {
      "name": "House of Chains II",
      "description": "Allows the recruitment of Mistresses of Chains and Bewitchers."
    },
    {
      "name": "Aga'Shoth Stables",
      "description": "Allows the recruitment of Aga’Shoth Riders."
    },
    {
      "name": "Aga'Shoth Stables II",
      "description": "Allows the recruitment of Aga’Shoth Tamers and Aga’Shoth Matha."
    },
    {
      "name": "Bloated Mansion",
      "description": "Allows the recruitment of Arbitrators."
    },
    {
      "name": "Bloated Mansion II",
      "description": "Allows the recruitment of Rift Arbitrators and Bloated Arbitrators."
    },
    {
      "name": "Lesser Summoning Rite",
      "description": "Allows the recruitment of Ra’Shoth."
    },
    {
      "name": "Lesser Summoning Rite II",
      "description": "Allows the recruitment of Stinging Ra’Shoth and Ferocious Ra’Shoth."
    },
    {
      "name": "Eerie Summoning Rite",
      "description": "Allows the recruitment of Abyssal Envoys."
    },
    {
      "name": "Eerie Summoning Rite II",
      "description": "Allows the recruitment of Abyssal Overseers and Abyssal Executors."
    },
    {
      "name": "Involuntary Summons",
      "description": "Once per week, allows the owner to recruit creatures from any one external dwelling under their control — even if there are no available units on the global map itself."
    },
    {
      "name": "Disturbing Summoning Rite",
      "description": "Allows the recruitment of Grand Shoth."
    },
    {
      "name": "Disturbing Summoning Rite II",
      "description": "Allows the recruitment of Unspeakable Shoth and Unthinkable Shoth."
    },
    {
      "name": "Mage Guild",
      "description": "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild II",
      "description": "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild III",
      "description": "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook."
    },
    {
      "name": "Mage Guild IV",
      "description": "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook."
    }
  ]
} as const;
