// Auto-generated by scripts/gen-law-seo.mjs — do not edit
export const lawSeo = {
  "hive": [
    {
      "title": "Resource Riches I",
      "description": "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted."
    },
    {
      "title": "Laws of the Hive",
      "description": "Requirements for unlocking higher-level Laws are reduced by 4."
    },
    {
      "title": "Mana Devour",
      "description": "Your heroes' spells const  -3 mana"
    },
    {
      "title": "Focus Reserves",
      "description": "Start each battle with +1 Focus Charge(s)."
    },
    {
      "title": "Tax Collectors",
      "description": "Produces 750 Gold daily."
    },
    {
      "title": "Mining: Crystals",
      "description": "Produces 2 Crystal(s) daily."
    },
    {
      "title": "Hidden Desires",
      "description": "Your Hive heroes see exact information about neutral squads within 9 squares."
    },
    {
      "title": "Resource Riches II",
      "description": "Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted."
    },
    {
      "title": "Natural Selection",
      "description": "External dwellings in an area that you control produce upgraded creatures."
    },
    {
      "title": "Ancient Power",
      "description": "Primal spells of your heroes gain 1 level(s)."
    },
    {
      "title": "Prosper and Flourish",
      "description": "External dwellings increase respective creature growth in the cities by 100."
    },
    {
      "title": "Beelzebub's Gaze",
      "description": "Your Hive heroes see exact information about enemy heroes and cities within 9 squares."
    },
    {
      "title": "Evolve, Adapt, Overcome",
      "description": "Upgrading your Hive creatures costs –20% Gold. Recruiting upgraded creatures is discounted by the same amount."
    },
    {
      "title": "Resource Riches III",
      "description": "Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted."
    },
    {
      "title": "Hive Magic",
      "description": "Your heroes deal +30% Magic Damage."
    },
    {
      "title": "Hive Integration",
      "description": "Friendly creatures gain 3 Attack."
    },
    {
      "title": "Hive Reception",
      "description": "Friendly creatures gain 3 Defense."
    },
    {
      "title": "Hive Offsprings I",
      "description": "Summoned Fire Larvae deal +50% Damage on death."
    },
    {
      "title": "Elite Parasites",
      "description": "Parasite growth in your cities increases by 4. They gain 2 HP."
    },
    {
      "title": "Elite Locusts",
      "description": "Locust growth in your cities increases by 4. They gain 2 Speed."
    },
    {
      "title": "Elite Hornets",
      "description": "Hornet growth in your cities increases by 2. They gain 2 Initiative."
    },
    {
      "title": "Elite Scorpions",
      "description": "Hornet growth in your cities increases by 2. They gain 3 Initiative."
    },
    {
      "title": "Elite Reavers",
      "description": "Reaver growth in your cities increases by 1. They gain 5 Morale and 1 Luck."
    },
    {
      "title": "Elite Waurmos",
      "description": "Waurms growth in your cities increases by 1. They gain 5 Morale and 1 Luck."
    },
    {
      "title": "Hive Offsprings II",
      "description": "Summoned Fire Larvae provoke adjacent enemies to attack them over other units."
    },
    {
      "title": "Elite Hive Queens",
      "description": "Hive Queen growth in your cities increases by 1. They deal +10 Damage and gain 50 HP."
    },
    {
      "title": "Elite Hive Queens",
      "description": "When battling in the area you do not control, friendly creatures gain 6 Attack and Defense."
    },
    {
      "title": "Infernal Rage",
      "description": "Friendly creatures deal +2 Damage."
    },
    {
      "title": "No Compassion",
      "description": "The chance of Morale or Luck triggering for friendly creatures increases by 3% for each point of their Morale or Luck, respectively."
    },
    {
      "title": "Hive Offsprings III",
      "description": "Summoned Fire Larvae attack twice."
    }
  ],
  "necropolis": [
    {
      "title": "Resource Riches I",
      "description": "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted."
    },
    {
      "title": "Tax Collectors",
      "description": "Produces 1000 Gold daily."
    },
    {
      "title": "Animate Dead I",
      "description": "Your heroes gain +500 maximum Necromantic Energy."
    },
    {
      "title": "Gifts of the Afterlife",
      "description": "Your heroes gain 3 Luck."
    },
    {
      "title": "Elite Skeletons",
      "description": "Skeleton growth in your cities increases by 8. They gain 2 Attack and Defense."
    },
    {
      "title": "Elite Wight",
      "description": "Wight growth in your cities increases by 8. Their minimum Damage increases by 1."
    },
    {
      "title": "Black Death",
      "description": "Enemy creatures take +50% from Damage-over-time effects."
    },
    {
      "title": "Mining: Mercury",
      "description": "Produces 2 Mercury daily."
    },
    {
      "title": "Stand to the Death!",
      "description": "Your heroes gain 3 Defense."
    },
    {
      "title": "Animate Dead II",
      "description": "Your heroes gain +2.5% Necromancy Power."
    },
    {
      "title": "Laws of the Immortals",
      "description": "Your cities generate +30% Law points."
    },
    {
      "title": "Elite Undead Pets",
      "description": "Undead Pet growth in your cities increases by 4. They gain 2 Initiative."
    },
    {
      "title": "Elite Graverobber",
      "description": "Graverobber growth in your cities increases by 4. They summon +50% units."
    },
    {
      "title": "Death Equalizes All",
      "description": "Friendly creatures from different factions don’t decrease each other’s Morale."
    },
    {
      "title": "Resource Riches II",
      "description": "Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted."
    },
    {
      "title": "Moon's Grace",
      "description": "Nightshade spells of your heroes gain 1 level(s)."
    },
    {
      "title": "Animate Dead III",
      "description": "Your heroes gain +500 maximum Necromantic Energy."
    },
    {
      "title": "Forbidden Alchemy",
      "description": "Your spell upgrades cost –40% Alchemical Dust."
    },
    {
      "title": "Elite Liches",
      "description": "Lich growth in your cities increases by 2. Their healing abilities restore 50% more HP."
    },
    {
      "title": "Elite Dread Knights",
      "description": "Dread Knight growth in your cities increases by 2. Their maximum Damage increases by 6."
    },
    {
      "title": "Bloodthirst",
      "description": "Vampirism of friendly creatures increases by 60%."
    },
    {
      "title": "Free Death",
      "description": "Your Necropolis creatures cost –20% Gold."
    },
    {
      "title": "Terra Mortis",
      "description": "Your Necropolis heroes always battle on their Native Terrain."
    },
    {
      "title": "Animate Dead IV",
      "description": "Your heroes gain +2.5% Necromancy Power."
    },
    {
      "title": "Elite Vampires",
      "description": "Vampire growth in your cities increases by 2. They gain 25 HP."
    },
    {
      "title": "Return to the Soil",
      "description": "Friendly creatures battling on their Native terrain gain 2 Speed."
    },
    {
      "title": "Terror and Dread",
      "description": "The chance of Morale or Luck triggering for enemy creatures decreases by 2% for each point of their Morale or Luck, respectively."
    },
    {
      "title": "Resource Riches III",
      "description": "Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted."
    },
    {
      "title": "Magic Absorption",
      "description": "The enemy loses 1 level(s) on all Magic School spells."
    },
    {
      "title": "Animate Dead V",
      "description": "Your heroes gain +500 maximum Necromantic Energy."
    },
    {
      "title": "Morituri te Salutant",
      "description": "Friendly creatures can make +1 counterattacks per round."
    },
    {
      "title": "Death's Presence",
      "description": "Enemy non-Necropolis creatures deal –10% and take +10% Damage. Your non-Necropolis creatures gain the opposite effect."
    }
  ],
  "grove": [
    {
      "title": "Resource Riches I",
      "description": "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted."
    },
    {
      "title": "Tax Collectors",
      "description": "Produces 500 Gold daily."
    },
    {
      "title": "Knowledge is Power",
      "description": "Your heroes gain 3 Knowledge."
    },
    {
      "title": "Elite Fauns",
      "description": "Faun growth in your cities increases by 6. They deal +50% Melee Damage."
    },
    {
      "title": "Elite Hoplet",
      "description": "Hoplet growth in your cities increases by 6. They always deal maximum Damage."
    },
    {
      "title": "Mining: Crystals",
      "description": "Produces 2 Crystal(s) daily."
    },
    {
      "title": "Clear Sky",
      "description": "Produces 250 Astrology Points daily."
    },
    {
      "title": "Folk Heroes",
      "description": "Your heroes cost –40% Gold."
    },
    {
      "title": "Elite Iriyads",
      "description": "Vine Iriyad growth in your cities increases by 2. They gain 15 HP."
    },
    {
      "title": "Nature's Wildness",
      "description": "Friendly creatures deal 50% more Damage with Lucky Strikes."
    },
    {
      "title": "Veiled by the Treess",
      "description": "When battling in the area you control, friendly creatures gain 6 Attack and Defense."
    },
    {
      "title": "Resource Riches II",
      "description": "Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted."
    },
    {
      "title": "Save the Forests",
      "description": "Your buildings cost –40% Wood to construct."
    },
    {
      "title": "Forest Magic",
      "description": "Each time you improve a Mage Guild in your Grove cities, +2 spell(s) is unlocked in the Observatory."
    },
    {
      "title": "Woodland Resistance",
      "description": "Enemies can’t see detailed information about your armies. (When viewed, it shows random numbers of random Grove units.)"
    },
    {
      "title": "Elite Naiads",
      "description": "Naiad growth in your cities increases by 2. They gain 3 Speed and Initiative."
    },
    {
      "title": "Nature's Resolve",
      "description": "All negative effects on friendly creatures last 1 fewer round(s)."
    },
    {
      "title": "Fertile Ground",
      "description": "Creature growth of your external dwellings increases by +200%."
    },
    {
      "title": "The Power of the Written Word",
      "description": "All temporary spells (scrolls, artifacts etc.) available to your heroes gain 3 level(s)."
    },
    {
      "title": "Natural Serenity",
      "description": "The cooldowns of all the battle spells of your heroes are reduced by 1 round(s)."
    },
    {
      "title": "Live roots",
      "description": "Enemy heroes can’t flee or surrender."
    },
    {
      "title": "Elite Mancers",
      "description": "Herbomancer growth in your cities increases by 3. Their abilities cost –1 Focus Charge(s)."
    },
    {
      "title": "Elite Qilin",
      "description": "Qilin growth in your cities increases by 1. They deal +9 Damage."
    },
    {
      "title": "Luck of the Fittest",
      "description": "Friendly creatures now have +3% Lucky Strike chance for each point of Luck."
    },
    {
      "title": "Resource Riches III",
      "description": "Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted."
    },
    {
      "title": "Force of Nature",
      "description": "Your Heroic Strikes deal +20 basic Damage."
    },
    {
      "title": "Children of the Wild",
      "description": "Your Grove heroes gain 4 sight radius and 20 Movement points."
    },
    {
      "title": "Focus",
      "description": "Each round of battle, you generate 1 Focus Charge(s)."
    },
    {
      "title": "Elite Phoenixes",
      "description": "Phoenix growth in your cities increases by 1. Their maximum Damage increases by 20."
    },
    {
      "title": "Fairy Tale",
      "description": "Your Fauns, Hoplets and Herbomancers gain 2 Speed and Initiative."
    },
    {
      "title": "Sanctuary",
      "description": "The abilities of your Vine Iriyads, Naiads, Qilins and Phoenixes cost –1 Focus Charge(s)."
    }
  ],
  "dungeon": [
    {
      "title": "Resource Riches I",
      "description": "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted."
    },
    {
      "title": "Arcane Knowledge",
      "description": "Produces 500 Astrology points daily."
    },
    {
      "title": "Leaders of the Nation",
      "description": "Your heroes generate 20% Law points."
    },
    {
      "title": "Elite Troglodytes",
      "description": "Your Troglodytes deal 1.5 times more Damage when using their Fighting Style. Their min. Damage increases by 2."
    },
    {
      "title": "Dungeon Masters I",
      "description": "Tier-1 creature growth in your cities increases by 4."
    },
    {
      "title": "Dragon Scales",
      "description": "Friendly creatures take –15% Magic Damage."
    },
    {
      "title": "Tax Collectors",
      "description": "Produces 500 Gold daily."
    },
    {
      "title": "Mining: Gems",
      "description": "Produces 2 Gem(s) daily."
    },
    {
      "title": "Alchemists Code I",
      "description": "Provides a one-time allotment of 75 Alchemical Dust when enacted."
    },
    {
      "title": "Elite Infiltrators",
      "description": "Your Infiltrators deal 1.5 times more Damage when using their Fighting Style. They gain 4 HP."
    },
    {
      "title": "Elite Dancers",
      "description": "Your Onyx Dancers deal 1.5 times more Damage when using their Fighting Style. They gain 4 Attack and Defense."
    },
    {
      "title": "Dungeon Masters II",
      "description": "Tier-2 creature growth in your cities increases by 4."
    },
    {
      "title": "Dungeon Masters III",
      "description": "Tier-3 creature growth in your cities increases by 2."
    },
    {
      "title": "Resource Riches II",
      "description": "Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted."
    },
    {
      "title": "Or No Ore?",
      "description": "Your buildings cost –40% Ore to construct."
    },
    {
      "title": "Jadame Maps",
      "description": "Your heroes gain 20 Movement points."
    },
    {
      "title": "Spy Network",
      "description": "All external buildings and structures under your control gain +6 sight radius."
    },
    {
      "title": "Elite Minotaurs",
      "description": "Your Minotaurs deal 1.5 times more Damage when using their Fighting Style. They gain 1 Speed and Initiative and deal +4 Damage."
    },
    {
      "title": "Elite Medusae",
      "description": "Your Medusae deal 1.5 times more Damage when using their Fighting Style. They gain 2 Initiative and 4 Attack and Defense."
    },
    {
      "title": "Tactical Advantage",
      "description": "All enemy creatures lose 1 Initiative."
    },
    {
      "title": "Dungeon Masters IV",
      "description": "Tier-4 creature growth in your cities increases by 2."
    },
    {
      "title": "Merchants Guild",
      "description": "Eliminates all price markups in the Marketplace."
    },
    {
      "title": "Triumvirate's Agents",
      "description": "Your Dungeon heroes gain 2 to all attributes."
    },
    {
      "title": "Alchemists Code II",
      "description": "Provides a one-time allotment of 150 Alchemical Dust when enacted."
    },
    {
      "title": "Peoples of Jadame",
      "description": "Your heroes’ Persuasion Power in Diplomacy increases by 20%."
    },
    {
      "title": "Elite Hydras",
      "description": "Your Hydras deal 1.5 times more Damage when using their Fighting Style. They gain 2 Speed and 25 HP."
    },
    {
      "title": "Dungeon Masters V",
      "description": "Tier-5 creature growth in your cities increases by 1."
    },
    {
      "title": "Dungeon Masters VI",
      "description": "Tier-6 creature growth in your cities increases by 1."
    },
    {
      "title": "Resource Riches III",
      "description": "Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted."
    },
    {
      "title": "Magical Education",
      "description": "Spells of your heroes gain 2 level(s)."
    },
    {
      "title": "Saturation",
      "description": "Your Focus Charge limit increases by 1."
    },
    {
      "title": "Elite Cave Dragons",
      "description": "Your Cave Dragons deal 1.5 times more Damage, when using their Fighting Style. They gain 8 Attack and Defense and 2 Speed and Initiative."
    },
    {
      "title": "Dungeon Masters VII",
      "description": "Tier-7 creature growth in your cities increases by 1."
    }
  ],
  "temple": [
    {
      "title": "Resource Riches I",
      "description": "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted."
    },
    {
      "title": "Training: Scouting",
      "description": "Your heroes gain 1 Sight radius."
    },
    {
      "title": "Faith in Magic",
      "description": "Produces 250 Astrology points daily."
    },
    {
      "title": "Elite Swordsmen",
      "description": "Swordsman growth in your cities increases by 4. They gain 4 Defense."
    },
    {
      "title": "Elite Crossbowman",
      "description": "Crossbowman growth in your cities increases by 4. They gain 4 Attack."
    },
    {
      "title": "Inquisition Crusade",
      "description": "Friendly creatures deal +25% Damage to summoned enemy creatures."
    },
    {
      "title": "Tax Collectors",
      "description": "Produces 1000 Gold daily."
    },
    {
      "title": "Mining: Gems",
      "description": "Produces 2 Gem(s) daily."
    },
    {
      "title": "Heroes of Tales",
      "description": "Your heroes gain 2 Morale."
    },
    {
      "title": "Elite Griffins",
      "description": "Griffin growth in your cities increases by 2. They gain 10 HP."
    },
    {
      "title": "Elite Lightweavers",
      "description": "Lightweaver growth in your cities increases by 2. They deal +4 Damage."
    },
    {
      "title": "Execute Excellence",
      "description": "All positive effects on friendly creatures last 2 additional round(s)."
    },
    {
      "title": "Swift Reflexes",
      "description": "Friendly creatures gain 1 Initiative."
    },
    {
      "title": "Resource Riches II",
      "description": "Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted."
    },
    {
      "title": "Coinage Reform",
      "description": "Your sources of Gold produce +20% Gold."
    },
    {
      "title": "Sun's Grace",
      "description": "Daylight spells of your heroes gain 1 level(s)."
    },
    {
      "title": "Architect's Mastery",
      "description": "You can construct +1 building(s) daily."
    },
    {
      "title": "Elite Cavalry",
      "description": "Cavalry growth in your cities increases by 1. Their attacks ignore 10% of the target’s Defense and they gain 1 Speed."
    },
    {
      "title": "Training: Melee Combat",
      "description": "Friendly creatures deal +10% and take –10% Melee Damage. This effect is doubled for non-Temple friendly creatures."
    },
    {
      "title": "Training: Range Combat",
      "description": "Friendly creatures deal +10% and take –10% Long Reach and Ranged Damage. This effect is doubled for non-Temple friendly creatures."
    },
    {
      "title": "Training: Attack",
      "description": "Your heroes gain 4 Attack."
    },
    {
      "title": "Training: Defense",
      "description": "Your heroes gain 4 Defense."
    },
    {
      "title": "Training: Spell Power",
      "description": "Your heroes gain 4 Spell Power."
    },
    {
      "title": "Training: Knowledge",
      "description": "Your heroes gain 4 Knowledge."
    },
    {
      "title": "Elite Inquisitors",
      "description": "Inquisitor growth in your cities increases by 1. They ignore 10% of the enemy’s Attack and they gain 1 Speed."
    },
    {
      "title": "Encouragement",
      "description": "The chance of Morale triggering for friendly creatures increases by 3% for each point of their Morale."
    },
    {
      "title": " Vengeful Strike",
      "description": "Friendly creatures’ counterattacks deal +50%/100% Damage."
    },
    {
      "title": "Resource Riches III",
      "description": "Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted."
    },
    {
      "title": "Power of Faith",
      "description": "All your Temple heroes can learn any spells of any tier."
    },
    {
      "title": "Elite Angels",
      "description": "Angel growth in your cities increases by 1. They gain 50% of their hero’s Attack and Defense as Attack and Defense."
    },
    {
      "title": "Hero's Blessing",
      "description": "Friendly creatures gain 25% of their hero’s Spell Power and Knowledge as Attack and Defense respectively."
    },
    {
      "title": "Sacred Lands",
      "description": "Friendly creatures are immune to negative effects when fighting on their Native Terrain."
    }
  ],
  "schism": [
    {
      "title": "Resource Riches I",
      "description": "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted."
    },
    {
      "title": "Inevitable Destruction",
      "description": "When destroying artifacts, you gain +30% Alchemical Dust."
    },
    {
      "title": "Depths of Mind",
      "description": "Your Schism heroes restore +15% mana each morning."
    },
    {
      "title": "Elite Ra'Shoth",
      "description": "Ra’Shoth growth in your cities increases by 8. They gain 1 Initiative."
    },
    {
      "title": "Unfrozen Strength I",
      "description": "Tier-1 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense."
    },
    {
      "title": "Frozen Homeland",
      "description": "Friendly creatures gain 3 Attack and Defense when they battle on their Native Terrain."
    },
    {
      "title": "Tax Collectors",
      "description": "Produces 500 Gold daily."
    },
    {
      "title": "Mining: Mercury",
      "description": "Produces 2 Mercury daily."
    },
    {
      "title": "Generational Wisdom",
      "description": "Your heroes gain +20% XP."
    },
    {
      "title": "Ice Power",
      "description": "Your heroes gain +3 Spell Power."
    },
    {
      "title": "Elite Cultists",
      "description": "Cultist growth in your cities increases by 4. They deal +1 Damage."
    },
    {
      "title": "Elite Aga'Shoth Riders",
      "description": "Aga’Shoth Rider growth in your cities increases by 2. They gain 5 HP."
    },
    {
      "title": "Unfrozen Strength II",
      "description": "Tier-2 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack,10% of their Defense and Knowledge as Defense."
    },
    {
      "title": "Unfrozen Strength III",
      "description": "Tier-3 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense."
    },
    {
      "title": "Resource Riches II",
      "description": "Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted."
    },
    {
      "title": "Otherworldly Magic",
      "description": "Arcane spells of your heroes gain 1 level."
    },
    {
      "title": "Call of the Deep",
      "description": "Your Schism heroes’ spells and friendly creatures’ abilities summon +30% units."
    },
    {
      "title": "Elite Grand Shoth",
      "description": "Grand Shoth growth in your cities increases by 4. They gain 1 Speed."
    },
    {
      "title": "Unfrozen Strength IV",
      "description": "Tier-4 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense."
    },
    {
      "title": "Cold Touch",
      "description": "All effects applied by your heroes and friendly creatures last 2 additional round(s)."
    },
    {
      "title": "Survival Conditions",
      "description": "Your cities produce +2 Wood and Ore."
    },
    {
      "title": "Planar Explorers",
      "description": "Produces 1500 Astrology points daily."
    },
    {
      "title": "Absolute Zero",
      "description": "The cooldowns of all the battle spells of enemy heroes are increased by 1 round(s)."
    },
    {
      "title": "Cold Shoulder",
      "description": "You can use Involuntary Summons in your Schism cities twice per week."
    },
    {
      "title": "Elite Concubi",
      "description": "Concubus growth in your cities increases by 1. They gain 4 Attack and Defense."
    },
    {
      "title": "Elite Arbitrators",
      "description": "Arbitrator growth in your cities increases by 1. They deal +4 Damage."
    },
    {
      "title": "Unfrozen Strength V",
      "description": "Tier-5 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense."
    },
    {
      "title": "Unfrozen Strength VI",
      "description": "Tier-6 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense."
    },
    {
      "title": "Resource Riches III",
      "description": "Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted."
    },
    {
      "title": "Mind Freeze",
      "description": "Each round of battle, the enemy loses 1 Focus Charge(s)."
    },
    {
      "title": "The Abyss Stares Back",
      "description": "Your Schism heroes start each day with maximum Communion level."
    },
    {
      "title": "The World is Ours",
      "description": "Friendly creatures treat all Terrains as Native."
    },
    {
      "title": "Elite Abyssal Envoys",
      "description": "Abyssal Envoy growth in your cities increases by 2. They gain 2 Speed and Initiative."
    },
    {
      "title": "Unfrozen strength VII",
      "description": "Tier-7 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense."
    },
    {
      "title": "Ice Storms",
      "description": "All enemy creatures lose 1 Speed and Initiative."
    }
  ]
} as const;
