export const castles = {
  hive: {
    id10: {
      id: "id10",
      name: "Tavern",
      prev: null,
      next: ["id20"],
      pos: [1, 0],
      cost: {
        gold: 500,
        wood: 0,
        ore: 5,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
    },
    id20: {
      id: "id20",
      name: "Marketplace",
      prev: ["id10"],
      next: ["id31"],
      pos: [2, 0],
      cost: {
        gold: 500,
        wood: 5,
        ore: 0,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id01: {
      id: "id01",
      name: "Apiary's Heart",
      prev: null,
      next: ["id11"],
      pos: [0, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 15,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      produces: {
        gold: 500,
        law: 500,
        astrology: 500,
      },
      isMarked: false,
    },
    id11: {
      id: "id11",
      name: "Apiary's Heart II",
      prev: ["id01"],
      next: ["id21", "id20", "id22"],
      pos: [1, 1],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id21: {
      id: "id21",
      name: "Apiary's Heart III",
      prev: ["id11"],
      next: null,
      pos: [2, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 10,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id31: {
      id: "id31",
      name: "Resource Depot",
      prev: ["id20", "id22"],
      next: ["id41"],
      pos: [3, 1],
      cost: {
        gold: 2000,
        wood: 0,
        ore: 0,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
      produces: {
        crystal: 1,
      },
    },
    id41: {
      id: "id41",
      name: "Alchemic Depot",
      prev: ["id31"],
      next: null,
      pos: [4, 1],
      cost: {
        gold: 0,
        wood: 0,
        ore: 0,
        gems: 3,
        crystals: 3,
        mercury: 3,
        dust: 0,
      },
      isMarked: false,
      
      produces: {
        dust: 5,
      },
    },
    id02: {
      id: "id02",
      name: "Beelzebub's Hand",
      prev: null,
      next: null,
      pos: [0, 2],
      cost: {
        gold: 5000,
        wood: 0,
        ore: 0,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id22: {
      id: "id22",
      name: "Bank",
      prev: ["id11"],
      next: ["id31", "id32"],
      pos: [2, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
      produces: {
        gold: 1000,
      },
    },
    id32: {
      id: "id32",
      name: "Treasury",
      prev: ["id22", "id23"],
      next: null,
      pos: [3, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
      produces: {
        gold: 1000,
      },
    },
    id23: {
      id: "id23",
      name: "Fortifications",
      prev: null,
      next: ["id24"],
      pos: [2, 3],
      cost: {
        gold: 2500,
        wood: 0,
        ore: 5,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id33: {
      id: "id33",
      name: "Fortifications II",
      prev: ["id23"],
      next: ["id43"],
      pos: [3, 3],
      cost: {
        gold: 2500,
        wood: 0,
        ore: 10,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id43: {
      id: "id43",
      name: "Fortifications III",
      prev: ["id33"],
      next: null,
      pos: [4, 3],
      cost: {
        gold: 5000,
        wood: 0,
        ore: 15,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id14: {
      id: "id14",
      name: "Paper nest",
      prev: null,
      next: ["id24", "id24"],
      pos: [1, 4],
      cost: {
        gold: 3000,
        wood: 10,
        ore: 0,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id24: {
      id: "id24",
      name: "Paper nest II",
      prev: ["id14"],
      next: null,
      pos: [2, 4],
      cost: {
        gold: 750,
        wood: 10,
        ore: 0,
        gems: 0,
        crystals: 10,
        mercury: 0,
        dust: 30,
      },
      isMarked: false,
      
    },
    id34: {
      id: "id34",
      name: "Sacrarium Rediti",
      prev: ["id23"],
      next: null,
      pos: [3, 4],
      cost: {
        gold: 2500,
        wood: 0,
        ore: 0,
        gems: 5,
        crystals: 5,
        mercury: 5,
        dust: 0,
      },
      isMarked: false,
      
    },
    id05: {
      id: "id05",
      name: "Carrion Lair",
      prev: null,
      next: ["id15"],
      pos: [0, 5],
      cost: {
        gold: 2500,
        wood: 0,
        ore: 0,
        gems: 5,
        crystals: 5,
        mercury: 5,
        dust: 0,
      },
      isMarked: false,
    },
    id15: {
      id: "id15",
      name: "Carrion Lair II",
      prev: ["id05"],
      next: null,
      pos: [1, 5],
      cost: {
        gold: 1500,
        wood: 0,
        ore: 0,
        gems: 0,
        crystals: 5,
        mercury: 0,
        dust: 20,
      },
      isMarked: false,
      
    },
    id25: {
      id: "id25",
      name: "Burning Soul Burrows",
      prev: ["id14", "id17"],
      next: ["id35", "id36"],
      pos: [2, 5],
      cost: {
        gold: 6000,
        wood: 0,
        ore: 10,
        gems: 0,
        crystals: 5,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id35: {
      id: "id35",
      name: "Tower of Love",
      prev: ["id25"],
      next: ["id45"],
      pos: [3, 5],
      cost: {
        gold: 15000,
        wood: 0,
        ore: 0,
        gems: 0,
        crystals: 15,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id45: {
      id: "id45",
      name: "Tower of Love II",
      prev: ["id35"],
      next: null,
      pos: [4, 5],
      cost: {
        gold: 15000,
        wood: 0,
        ore: 0,
        gems: 0,
        crystals: 25,
        mercury: 0,
        dust: 100,
      },
      isMarked: false,
      
    },
    id06: {
      id: "id06",
      name: "Neglected Housing",
      prev: null,
      next: ["id16", "id17"],
      pos: [0, 6],
      cost: {
        gold: 0,
        wood: 0,
        ore: 0,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
    },
    id16: {
      id: "id16",
      name: "Neglected Housing II",
      prev: ["id06"],
      next: null,
      pos: [1, 6],
      cost: {
        gold: 500,
        wood: 0,
        ore: 0,
        gems: 0,
        crystals: 5,
        mercury: 0,
        dust: 10,
      },
      isMarked: false,
      
    },
    id26: {
      id: "id26",
      name: "Chitinous Ziggurat II",
      prev: ["id17"],
      next: null,
      pos: [2, 6],
      cost: {
        gold: 1500,
        wood: 0,
        ore: 10,
        gems: 0,
        crystals: 5,
        mercury: 0,
        dust: 40,
      },
      isMarked: false,
      
    },
    id36: {
      id: "id36",
      name: "Burning Soul Burrows II",
      prev: ["id25"],
      next: null,
      pos: [3, 6],
      cost: {
        gold: 4000,
        wood: 0,
        ore: 5,
        gems: 0,
        crystals: 15,
        mercury: 0,
        dust: 75,
      },
      isMarked: false,
      
    },
    id17: {
      id: "id17",
      name: "Chitinous Ziggurat",
      prev: ["id06"],
      next: ["id16", "id15", "id14"],
      pos: [1, 7],
      cost: {
        gold: 3750,
        wood: 0,
        ore: 10,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id27: {
      id: "id27",
      name: "Apex",
      prev: ["id17"],
      next: ["id37"],
      pos: [2, 7],
      cost: {
        gold: 5500,
        wood: 10,
        ore: 0,
        gems: 0,
        crystals: 5,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id37: {
      id: "id37",
      name: "Apex",
      prev: ["id27"],
      next: null,
      pos: [3, 7],
      cost: {
        gold: 4000,
        wood: 5,
        ore: 0,
        gems: 0,
        crystals: 10,
        mercury: 0,
        dust: 50,
      },
      isMarked: false,
      
    },
    id08: {
      id: "id08",
      name: "Mage Guild",
      prev: null,
      next: ["id18"],
      pos: [0, 8],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 0,
        gems: 0,
        crystals: 0,
        mercury: 0,
        dust: 0,
      },
      isMarked: false,
      
    },
    id18: {
      id: "id18",
      name: "Mage Guild II",
      prev: ["id08"],
      next: ["id28"],
      pos: [1, 8],
      cost: {
        gold: 2500,
        wood: 0,
        ore: 0,
        gems: 2,
        crystals: 2,
        mercury: 2,
        dust: 0,
      },
      isMarked: false,
      
    },
    id28: {
      id: "id28",
      name: "Mage Guild III",
      prev: ["id18"],
      next: ["id38"],
      pos: [2, 8],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 0,
        gems: 3,
        crystals: 3,
        mercury: 3,
        dust: 0,
      },
      isMarked: false,
      
    },
    id38: {
      id: "id38",
      name: "Mage Guild IV",
      prev: ["id28"],
      next: ["id48"],
      pos: [3, 8],
      cost: {
        gold: 2500,
        wood: 0,
        ore: 0,
        gems: 5,
        crystals: 5,
        mercury: 5,
        dust: 0,
      },
      isMarked: false,
      
    },
    id48: {
      id: "id48",
      name: "Mage Guild V",
      prev: ["id38"],
      next: null,
      pos: [4, 8],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 0,
        gems: 5,
        crystals: 5,
        mercury: 5,
        dust: 0,
      },
      isMarked: false,
      
    },
  },
} as const;

export const castlePreBuilds = {
  hive: ["id10", "id01", "id05", "id06"]
}
