export const castles = {
  hive: {
    id00: {
      id: "id00",
      name: "Chorus Conductor",
      prev: null,
      next: null,
      pos: [0, 0],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id10: {
      id: "id10",
      name: "Tavern",
      prev: null,
      next: ["id20"],
      pos: [1, 0],
      cost: {
        gold: 500,
        ore: 5,
      },
      produces: {},
    },
    id20: {
      id: "id20",
      name: "Marketplace",
      prev: ["id10"],
      next: ["id31"],
      pos: [2, 0],
      cost: {
        gold: 500,
        wood: 5,
      },
      produces: {},
    },
    id01: {
      id: "id01",
      name: "Apiary's Heart",
      prev: null,
      next: ["id11"],
      pos: [0, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 15,
      },
      produces: {
        gold: 500,
        law: 500,
        astrology: 500,
      },
    },
    id11: {
      id: "id11",
      name: "Apiary's Heart II",
      prev: ["id01"],
      next: ["id21", "id22"],
      pos: [1, 1],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id21: {
      id: "id21",
      name: "Apiary's Heart III",
      prev: ["id11"],
      next: null,
      pos: [2, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id31: {
      id: "id31",
      name: "Resource Depot",
      prev: ["id20", "id22"],
      next: ["id41"],
      pos: [3, 1],
      cost: {
        gold: 2000,
      },
      produces: {
        crystals: 1,
      },
    },
    id41: {
      id: "id41",
      name: "Alchemic Depot",
      prev: ["id31"],
      next: null,
      pos: [4, 1],
      cost: {
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {
        dust: 5,
      },
    },
    id02: {
      id: "id02",
      name: "Beelzebub's Hand",
      prev: null,
      next: null,
      pos: [0, 2],
      cost: {
        gold: 5000,
      },
      produces: {},
    },
    id22: {
      id: "id22",
      name: "Bank",
      prev: ["id11"],
      next: ["id31", "id32"],
      pos: [2, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 1000,
      },
    },
    id32: {
      id: "id32",
      name: "Treasury",
      prev: ["id22", "id23"],
      next: null,
      pos: [3, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 2000,
      },
    },
    id23: {
      id: "id23",
      name: "Fortifications",
      prev: null,
      next: ["id33", "id34"],
      pos: [2, 3],
      cost: {
        gold: 2500,
        ore: 5,
      },
      produces: {},
    },
    id33: {
      id: "id33",
      name: "Fortifications II",
      prev: ["id23"],
      next: ["id43"],
      pos: [3, 3],
      cost: {
        gold: 2500,
        ore: 10,
      },
      produces: {},
    },
    id43: {
      id: "id43",
      name: "Fortifications III",
      prev: ["id33"],
      next: null,
      pos: [4, 3],
      cost: {
        gold: 5000,
        ore: 15,
      },
      produces: {},
    },
    id14: {
      id: "id14",
      name: "Paper nest",
      prev: null,
      next: ["id24", "id24"],
      pos: [1, 4],
      cost: {
        gold: 3000,
        wood: 10,
      },
      produces: {},
    },
    id24: {
      id: "id24",
      name: "Paper nest II",
      prev: ["id14"],
      next: null,
      pos: [2, 4],
      cost: {
        gold: 750,
        wood: 10,

        crystals: 10,
        dust: 30,
      },
      produces: {},
    },
    id34: {
      id: "id34",
      name: "Sacrarium Rediti",
      prev: ["id23"],
      next: null,
      pos: [3, 4],
      cost: {
        gold: 2500,

        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id05: {
      id: "id05",
      name: "Carrion Lair",
      prev: null,
      next: ["id15"],
      pos: [0, 5],
      cost: {
        gold: 2500,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id15: {
      id: "id15",
      name: "Carrion Lair II",
      prev: ["id05"],
      next: null,
      pos: [1, 5],
      cost: {
        gold: 1500,

        crystals: 5,
        dust: 20,
      },
      produces: {},
    },
    id25: {
      id: "id25",
      name: "Burning Soul Burrows",
      prev: ["id14", "id17"],
      next: ["id35", "id36"],
      pos: [2, 5],
      cost: {
        gold: 6000,
        ore: 10,
        crystals: 5,
      },
      produces: {},
    },
    id35: {
      id: "id35",
      name: "Tower of Love",
      prev: ["id25"],
      next: ["id45"],
      pos: [3, 5],
      cost: {
        gold: 15000,
        crystals: 15,
      },
      produces: {},
    },
    id45: {
      id: "id45",
      name: "Tower of Love II",
      prev: ["id35"],
      next: null,
      pos: [4, 5],
      cost: {
        gold: 15000,
        crystals: 25,
        dust: 100,
      },
      produces: {},
    },
    id06: {
      id: "id06",
      name: "Neglected Housing",
      prev: null,
      next: ["id16", "id17"],
      pos: [0, 6],
      cost: {},
      produces: {},
    },
    id16: {
      id: "id16",
      name: "Neglected Housing II",
      prev: ["id06"],
      next: null,
      pos: [1, 6],
      cost: {
        gold: 500,
        crystals: 5,
        dust: 10,
      },
      produces: {},
    },
    id26: {
      id: "id26",
      name: "Chitinous Ziggurat II",
      prev: ["id17"],
      next: null,
      pos: [2, 6],
      cost: {
        gold: 1500,
        ore: 10,
        crystals: 5,
        dust: 40,
      },
      produces: {},
    },
    id36: {
      id: "id36",
      name: "Burning Soul Burrows II",
      prev: ["id25"],
      next: null,
      pos: [3, 6],
      cost: {
        gold: 4000,
        ore: 5,
        crystals: 15,
        dust: 75,
      },
      produces: {},
    },
    id17: {
      id: "id17",
      name: "Chitinous Ziggurat",
      prev: ["id06"],
      next: ["id27", "id26", "id25"],
      pos: [1, 7],
      cost: {
        gold: 3750,
        ore: 10,
      },
      produces: {},
    },
    id27: {
      id: "id27",
      name: "Apex",
      prev: ["id17"],
      next: ["id37"],
      pos: [2, 7],
      cost: {
        gold: 5500,
        wood: 10,
        crystals: 5,
      },
      produces: {},
    },
    id37: {
      id: "id37",
      name: "Apex II",
      prev: ["id27"],
      next: null,
      pos: [3, 7],
      cost: {
        gold: 4000,
        wood: 5,
        crystals: 10,
        dust: 50,
      },
      produces: {},
    },
    id08: {
      id: "id08",
      name: "Mage Guild",
      prev: null,
      next: ["id18"],
      pos: [0, 8],
      cost: {
        gold: 2500,
        wood: 5,
      },
      produces: {},
    },
    id18: {
      id: "id18",
      name: "Mage Guild II",
      prev: ["id08"],
      next: ["id28"],
      pos: [1, 8],
      cost: {
        gold: 2500,
        gems: 2,
        crystals: 2,
        mercury: 2,
      },
      produces: {},
    },
    id28: {
      id: "id28",
      name: "Mage Guild III",
      prev: ["id18"],
      next: ["id38"],
      pos: [2, 8],
      cost: {
        gold: 2500,
        wood: 5,
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {},
    },
    id38: {
      id: "id38",
      name: "Mage Guild IV",
      prev: ["id28"],
      next: ["id48"],
      pos: [3, 8],
      cost: {
        gold: 2500,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id48: {
      id: "id48",
      name: "Mage Guild V",
      prev: ["id38"],
      next: null,
      pos: [4, 8],
      cost: {
        gold: 5000,
        wood: 10,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
  },
  necropolis: {
    id00: {
      id: "id00",
      name: "Everserpent",
      prev: null,
      next: null,
      pos: [0, 0],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id10: {
      id: "id10",
      name: "Tavern",
      prev: null,
      next: ["id20"],
      pos: [1, 0],
      cost: {
        gold: 500,
        ore: 5,
      },
      produces: {},
    },
    id20: {
      id: "id20",
      name: "Marketplace",
      prev: ["id10"],
      next: ["id31"],
      pos: [2, 0],
      cost: {
        gold: 500,
        wood: 5,
      },
      produces: {},
    },
    id01: {
      id: "id01",
      name: "Eternal Visage",
      prev: null,
      next: ["id11"],
      pos: [0, 1],
      cost: {
        gold: 0,
      },
      produces: {
        gold: 500,
        law: 500,
        astrology: 500,
      },
    },
    id11: {
      id: "id11",
      name: "Eternal Visage II",
      prev: ["id01"],
      next: ["id21", "id22"],
      pos: [1, 1],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id21: {
      id: "id21",
      name: "Eternal Visage III",
      prev: ["id11"],
      next: null,
      pos: [2, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id31: {
      id: "id31",
      name: "Resource Depot",
      prev: ["id20", "id22"],
      next: ["id41"],
      pos: [3, 1],
      cost: {
        gold: 2000,
      },
      produces: {
        mercury: 1,
      },
    },
    id41: {
      id: "id41",
      name: "Alchemic Depot",
      prev: ["id31"],
      next: null,
      pos: [4, 1],
      cost: {
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {
        dust: 5,
      },
    },
    id22: {
      id: "id22",
      name: "Bank",
      prev: ["id11"],
      next: ["id31", "id32"],
      pos: [2, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 1000,
      },
    },
    id32: {
      id: "id32",
      name: "Treasury",
      prev: ["id22", "id23"],
      next: null,
      pos: [3, 2],
      cost: {
        gold: 5000,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {
        gold: 2000,
      },
    },
    id23: {
      id: "id23",
      name: "Fortifications",
      prev: null,
      next: ["id33"],
      pos: [2, 3],
      cost: {
        gold: 2500,
        ore: 5,
      },
      produces: {},
    },
    id33: {
      id: "id33",
      name: "Fortifications II",
      prev: ["id23"],
      next: ["id43"],
      pos: [3, 3],
      cost: {
        gold: 2500,
        ore: 10,
      },
      produces: {},
    },
    id43: {
      id: "id43",
      name: "Fortifications III",
      prev: ["id33"],
      next: null,
      pos: [4, 3],
      cost: {
        gold: 5000,
        ore: 15,
      },
      produces: {},
    },
    id04: {
      id: "id04",
      name: "Undead Transformer",
      prev: null,
      next: null,
      pos: [0, 4],
      cost: {
        gold: 1000,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id14: {
      id: "id14",
      name: "Kennel",
      prev: ["id05"],
      next: ["id34", "id25"],
      pos: [1, 4],
      cost: {
        gold: 2750,
        wood: 10,
      },
      produces: {},
    },
    id34: {
      id: "id34",
      name: "Tomb of the Warriors",
      prev: ["id14", "id23"],
      next: ["id44"],
      pos: [3, 4],
      cost: {
        gold: 7000,
        wood: 5,
        ore: 10,
      },
      produces: {},
    },
    id44: {
      id: "id44",
      name: "Tomb of the Warriors II",
      prev: ["id34"],
      next: null,
      pos: [4, 4],
      cost: {
        gold: 5000,
        ore: 15,
        mercury: 10,
        dust: 75,
      },
      produces: {},
    },
    id05: {
      id: "id05",
      name: "Crypts and Graves",
      prev: null,
      next: ["id15", "id16", "id14"],
      pos: [0, 5],
      cost: {},
      produces: {},
    },
    id15: {
      id: "id15",
      name: "Crypts and Graves II",
      prev: ["id05"],
      next: null,
      pos: [1, 5],
      cost: {
        gold: 1000,
        dust: 10,
      },
      produces: {},
    },
    id25: {
      id: "id25",
      name: "Kennel II",
      prev: ["id14"],
      next: null,
      pos: [2, 5],
      cost: {
        gold: 2500,
        wood: 5,
        dust: 30,
      },
      produces: {},
    },
    id35: {
      id: "id35",
      name: "Timeless Mansion II",
      prev: ["id26"],
      next: null,
      pos: [3, 5],
      cost: {
        gold: 2000,
        mercury: 10,
        dust: 50,
      },
      produces: {},
    },
    id16: {
      id: "id16",
      name: "Bone Exchange",
      prev: ["id05", "id07"],
      next: ["id26", "id27"],
      pos: [1, 6],
      cost: {
        gold: 4500,
        wood: 5,
        ore: 5,
        mercury: 5,
      },
      produces: {},
    },
    id26: {
      id: "id26",
      name: "Timeless Mansion",
      prev: ["id16"],
      next: ["id36", "id35"],
      pos: [2, 6],
      cost: {
        gold: 3500,
        wood: 5,
        ore: 5,
        mercury: 5,
      },
      produces: {},
    },
    id36: {
      id: "id36",
      name: "Chateau of Feasts",
      prev: ["id26"],
      next: ["id46"],
      pos: [3, 6],
      cost: {
        gold: 12500,
        wood: 15,
        ore: 15,
        mercury: 15,
      },
      produces: {},
    },
    id46: {
      id: "id46",
      name: "Chateau of Feasts II",
      prev: ["id36"],
      next: null,
      pos: [4, 6],
      cost: {
        gold: 17500,
        wood: 5,
        ore: 5,
        mercury: 25,
        dust: 100,
      },
      produces: {},
    },
    id07: {
      id: "id07",
      name: "Quiet Pavilion",
      prev: null,
      next: ["id17", "id16"],
      pos: [0, 7],
      cost: {
        gold: 1250,
        mercury: 5,
        dust: 20,
      },
      produces: {},
    },
    id17: {
      id: "id17",
      name: "Quiet Pavilion II",
      prev: ["id07"],
      next: null,
      pos: [1, 7],
      cost: {
        gold: 1250,
        mercury: 5,
        dust: 20,
      },
      produces: {},
    },
    id27: {
      id: "id27",
      name: "Bone Exchange II",
      prev: ["id16"],
      next: null,
      pos: [2, 7],
      cost: {
        gold: 3750,
        wood: 5,
        ore: 5,
        mercury: 5,
        dust: 40,
      },
      produces: {},
    },
    id37: {
      id: "id37",
      name: "Well of Souls",
      prev: ["id28"],
      next: null,
      pos: [3, 7],
      cost: {
        gold: 2500,
        mercury: 5,
        gems: 5,
        crystals: 5,
      },
      produces: {},
    },
    id08: {
      id: "id08",
      name: "Mage Guild",
      prev: null,
      next: ["id18"],
      pos: [0, 8],
      cost: {
        gold: 2500,
        wood: 5,
      },
      produces: {},
    },
    id18: {
      id: "id18",
      name: "Mage Guild II",
      prev: ["id08"],
      next: ["id28"],
      pos: [1, 8],
      cost: {
        gold: 2500,
        gems: 2,
        crystals: 2,
        mercury: 2,
      },
      produces: {},
    },
    id28: {
      id: "id28",
      name: "Mage Guild III",
      prev: ["id18"],
      next: ["id38"],
      pos: [2, 8],
      cost: {
        gold: 2500,
        wood: 5,
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {},
    },
    id38: {
      id: "id38",
      name: "Mage Guild IV",
      prev: ["id28"],
      next: ["id48"],
      pos: [3, 8],
      cost: {
        gold: 2500,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id48: {
      id: "id48",
      name: "Mage Guild V",
      prev: ["id38"],
      next: null,
      pos: [4, 8],
      cost: {
        gold: 5000,
        wood: 10,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
  },
  grove: {
    id00: {
      id: "id00",
      name: "Spring of Life",
      prev: null,
      next: null,
      pos: [0, 0],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id10: {
      id: "id10",
      name: "Tavern",
      prev: null,
      next: ["id20"],
      pos: [1, 0],
      cost: {
        gold: 500,
        ore: 5,
      },
      produces: {},
    },
    id20: {
      id: "id20",
      name: "Marketplace",
      prev: ["id10"],
      next: ["id31", "id30"],
      pos: [2, 0],
      cost: {
        gold: 500,
        wood: 5,
      },
      produces: {},
    },
    id30: {
      id: "id30",
      name: "Artifact Merchant",
      prev: ["id20"],
      next: null,
      pos: [3, 0],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id01: {
      id: "id01",
      name: "Grove Place",
      prev: null,
      next: ["id11"],
      pos: [0, 1],
      cost: {
        gold: 0,
      },
      produces: {
        gold: 500,
        law: 500,
        astrology: 500,
      },
    },
    id11: {
      id: "id11",
      name: "Grove Place II",
      prev: ["id01"],
      next: ["id21", "id22"],
      pos: [1, 1],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id21: {
      id: "id21",
      name: "Grove Place III",
      prev: ["id11"],
      next: null,
      pos: [2, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id31: {
      id: "id31",
      name: "Resource Depot",
      prev: ["id20", "id22"],
      next: ["id41"],
      pos: [3, 1],
      cost: {
        gold: 2000,
      },
      produces: {
        crystals: 1,
      },
    },
    id41: {
      id: "id41",
      name: "Alchemic Depot",
      prev: ["id31"],
      next: null,
      pos: [4, 1],
      cost: {
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {
        dust: 5,
      },
    },
    id02: {
      id: "id02",
      name: "Mother Nature",
      prev: null,
      next: null,
      pos: [0, 2],
      cost: {
        gold: 5000,
      },
      produces: {},
    },
    id22: {
      id: "id22",
      name: "Bank",
      prev: ["id11"],
      next: ["id31", "id32"],
      pos: [2, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 1000,
      },
    },
    id32: {
      id: "id32",
      name: "Treasury",
      prev: ["id22", "id23"],
      next: null,
      pos: [3, 2],
      cost: {
        gold: 5000,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {
        gold: 2000,
      },
    },
    id42: {
      id: "id42",
      name: "Mycelium Roots",
      prev: ["id33"],
      next: null,
      pos: [4, 2],
      cost: {
        gold: 5000,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id23: {
      id: "id23",
      name: "Fortifications",
      prev: null,
      next: ["id33"],
      pos: [2, 3],
      cost: {
        gold: 2500,
        ore: 5,
      },
      produces: {},
    },
    id33: {
      id: "id33",
      name: "Fortifications II",
      prev: ["id23"],
      next: ["id43", "id42"],
      pos: [3, 3],
      cost: {
        gold: 2500,
        ore: 10,
      },
      produces: {},
    },
    id43: {
      id: "id43",
      name: "Fortifications III",
      prev: ["id33"],
      next: null,
      pos: [4, 3],
      cost: {
        gold: 5000,
        ore: 15,
      },
      produces: {},
    },
    id14: {
      id: "id14",
      name: "Faun Huts II",
      prev: ["id05"],
      next: null,
      pos: [1, 4],
      cost: {
        gold: 750,
        wood: 5,
        dust: 10,
      },
      produces: {},
    },
    id24: {
      id: "id24",
      name: "Hop Patch II",
      prev: ["id15"],
      next: null,
      pos: [2, 4],
      cost: {
        gold: 1250,
        crystals: 5,
        dust: 20,
      },
      produces: {},
    },
    id05: {
      id: "id05",
      name: "Faun Huts",
      prev: null,
      next: ["id14"],
      pos: [0, 5],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id15: {
      id: "id15",
      name: "Hop Patch",
      prev: ["id05"],
      next: ["id24", "id25", "id26"],
      pos: [1, 5],
      cost: {
        gold: 1000,
        gems: 2,
        crystals: 2,
        mercury: 2,
      },
      produces: {},
    },
    id25: {
      id: "id25",
      name: "Shroomwood Shack",
      prev: ["id15"],
      next: ["id35"],
      pos: [2, 5],
      cost: {
        gold: 2750,
        wood: 10,
        gems: 4,
        crystals: 4,
        mercury: 4,
      },
      produces: {},
    },
    id35: {
      id: "id35",
      name: "Shroomwood Shack II",
      prev: ["id25"],
      next: null,
      pos: [3, 5],
      cost: {
        gold: 3250,
        wood: 20,
        crystals: 4,
        dust: 50,
      },
      produces: {},
    },
    id06: {
      id: "id06",
      name: "Menhir Circle",
      prev: null,
      next: ["id16", "id17"],
      pos: [0, 6],
      cost: {
        gold: 2000,
        wood: 5,
        ore: 5,
        crystals: 3,
      },
      produces: {},
    },
    id16: {
      id: "id16",
      name: "Menhir Circle II",
      prev: ["id06"],
      next: null,
      pos: [1, 6],
      cost: {
        gold: 1000,
        wood: 5,
        ore: 5,
        crystals: 3,
        dust: 30,
      },
      produces: {},
    },
    id26: {
      id: "id26",
      name: "Thunder Lair",
      prev: ["id15", "id17"],
      next: ["id36", "id37"],
      pos: [2, 6],
      cost: {
        gold: 6500,
        wood: 5,
        ore: 5,
        crystals: 5,
      },
      produces: {},
    },
    id36: {
      id: "id36",
      name: "Thunder Lair II",
      prev: ["id26"],
      next: null,
      pos: [3, 6],
      cost: {
        gold: 3500,
        wood: 10,
        ore: 10,
        crystals: 10,
        dust: 75,
      },
      produces: {},
    },
    id17: {
      id: "id17",
      name: "Booming Pond",
      prev: ["id06", "id08"],
      next: ["id27", "id26"],
      pos: [1, 7],
      cost: {
        gold: 2500,
        ore: 5,
        crystals: 5,
      },
      produces: {},
    },
    id27: {
      id: "id27",
      name: "Booming Pond II",
      prev: ["id17"],
      next: null,
      pos: [2, 7],
      cost: {
        gold: 1500,
        ore: 5,
        crystals: 5,
        dust: 40,
      },
      produces: {},
    },
    id37: {
      id: "id37",
      name: "Pyre",
      prev: ["id26"],
      next: ["id47"],
      pos: [3, 7],
      cost: {
        gold: 12500,
        wood: 5,
        ore: 5,
        crystals: 20,
      },
      produces: {},
    },
    id47: {
      id: "id47",
      name: "Pyre II",
      prev: ["id37"],
      next: null,
      pos: [4, 7],
      cost: {
        gold: 20000,
        wood: 5,
        ore: 5,
        crystals: 20,
        dust: 100,
      },
      produces: {},
    },
    id08: {
      id: "id08",
      name: "Mage Guild",
      prev: null,
      next: ["id18"],
      pos: [0, 8],
      cost: {
        gold: 2500,
        wood: 5,
      },
      produces: {},
    },
    id18: {
      id: "id18",
      name: "Mage Guild II",
      prev: ["id08"],
      next: ["id28"],
      pos: [1, 8],
      cost: {
        gold: 2500,
        gems: 2,
        crystals: 2,
        mercury: 2,
      },
      produces: {},
    },
    id28: {
      id: "id28",
      name: "Mage Guild III",
      prev: ["id18"],
      next: ["id38"],
      pos: [2, 8],
      cost: {
        gold: 2500,
        wood: 5,
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {},
    },
    id38: {
      id: "id38",
      name: "Mage Guild IV",
      prev: ["id28"],
      next: ["id48"],
      pos: [3, 8],
      cost: {
        gold: 2500,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id48: {
      id: "id48",
      name: "Mage Guild V",
      prev: ["id38"],
      next: null,
      pos: [4, 8],
      cost: {
        gold: 5000,
        wood: 10,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
  },
  dungeon: {
    id00: {
      id: "id00",
      name: "Spy Network",
      prev: null,
      next: null,
      pos: [0, 0],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id10: {
      id: "id10",
      name: "Tavern",
      prev: null,
      next: ["id20"],
      pos: [1, 0],
      cost: {
        gold: 500,
        ore: 5,
      },
      produces: {},
    },
    id20: {
      id: "id20",
      name: "Marketplace",
      prev: ["id10"],
      next: ["id31", "id30"],
      pos: [2, 0],
      cost: {
        gold: 500,
        wood: 5,
      },
      produces: {},
    },
    id30: {
      id: "id30",
      name: "Artifact Merchant",
      prev: ["id20"],
      next: null,
      pos: [3, 0],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id01: {
      id: "id01",
      name: "Byzantine Place",
      prev: null,
      next: ["id11"],
      pos: [0, 1],
      cost: {
        gold: 0,
      },
      produces: {
        gold: 500,
        law: 500,
        astrology: 500,
      },
    },
    id11: {
      id: "id11",
      name: "Byzantine Place II",
      prev: ["id01"],
      next: ["id21", "id22"],
      pos: [1, 1],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id21: {
      id: "id21",
      name: "Byzantine Place III",
      prev: ["id11"],
      next: null,
      pos: [2, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id31: {
      id: "id31",
      name: "Resource Depot",
      prev: ["id20", "id22"],
      next: ["id41"],
      pos: [3, 1],
      cost: {
        gold: 2000,
      },
      produces: {
        gems: 1,
      },
    },
    id41: {
      id: "id41",
      name: "Alchemic Depot",
      prev: ["id31"],
      next: null,
      pos: [4, 1],
      cost: {
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {
        dust: 5,
      },
    },
    id02: {
      id: "id02",
      name: "Gymnasium",
      prev: null,
      next: null,
      pos: [0, 2],
      cost: {
        gold: 5000,
      },
      produces: {},
    },
    id12: {
      id: "id12",
      name: "Lyceum",
      prev: null,
      next: null,
      pos: [1, 2],
      cost: {
        gold: 5000,
      },
      produces: {},
    },
    id22: {
      id: "id22",
      name: "Bank",
      prev: ["id11"],
      next: ["id31", "id32"],
      pos: [2, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 1000,
      },
    },
    id32: {
      id: "id32",
      name: "Treasury",
      prev: ["id22", "id23"],
      next: null,
      pos: [3, 2],
      cost: {
        gold: 5000,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {
        gold: 2000,
      },
    },
    id23: {
      id: "id23",
      name: "Fortifications",
      prev: null,
      next: ["id33"],
      pos: [2, 3],
      cost: {
        gold: 2500,
        ore: 5,
      },
      produces: {},
    },
    id33: {
      id: "id33",
      name: "Fortifications II",
      prev: ["id23"],
      next: ["id43", "id42"],
      pos: [3, 3],
      cost: {
        gold: 2500,
        ore: 10,
      },
      produces: {},
    },
    id43: {
      id: "id43",
      name: "Fortifications III",
      prev: ["id33"],
      next: null,
      pos: [4, 3],
      cost: {
        gold: 5000,
        ore: 15,
      },
      produces: {},
    },
    id04: {
      id: "id04",
      name: "Warren",
      prev: null,
      next: ["id14", "id15"],
      pos: [0, 4],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id14: {
      id: "id14",
      name: "Warren II",
      prev: null,
      next: ["id04"],
      pos: [1, 4],
      cost: {
        gold: 750,
        ore: 5,
        dust: 10,
      },
      produces: {},
    },
    id24: {
      id: "id24",
      name: "Amphitheater II",
      prev: ["id15"],
      next: ["id04"],
      pos: [2, 4],
      cost: {
        gold: 1250,
        ore: 5,
        gems: 2,
        dust: 30,
      },
      produces: {},
    },
    id15: {
      id: "id15",
      name: "Amphitheater",
      prev: ["id04", "id06"],
      next: ["id24", "id25"],
      pos: [1, 5],
      cost: {
        gold: 1250,
        ore: 5,
        gems: 2,
        dust: 30,
      },
      produces: {},
    },
    id25: {
      id: "id25",
      name: "Stilled Voices",
      prev: ["id15", "id17"],
      next: ["id35", "id36"],
      pos: [2, 5],
      cost: {
        gold: 2250,
        wood: 5,
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {},
    },
    id35: {
      id: "id35",
      name: "Stilled Voices II",
      prev: ["id25"],
      next: null,
      pos: [3, 5],
      cost: {
        gold: 2250,
        wood: 5,
        gems: 5,
        dust: 50,
      },
      produces: {},
    },
    id06: {
      id: "id06",
      name: "Safe House",
      prev: null,
      next: ["id16", "id15", "id17"],
      pos: [0, 6],
      cost: {
        gold: 1500,
        wood: 5,
        crystals: 1,
        gems: 1,
        mercury: 1,
      },
      produces: {},
    },
    id16: {
      id: "id16",
      name: "Safe House II",
      prev: ["id06"],
      next: null,
      pos: [1, 6],
      cost: {
        gold: 1250,
        wood: 5,
        gems: 1,
        dust: 20,
      },
      produces: {},
    },
    id26: {
      id: "id26",
      name: "Labyrinth II",
      prev: ["id17"],
      next: null,
      pos: [2, 6],
      cost: {
        gold: 3250,
        wood: 5,
        ore: 10,
        dust: 40,
      },
      produces: {},
    },
    id36: {
      id: "id36",
      name: "Chthonic Home",
      prev: ["id25"],
      next: ["id46"],
      pos: [3, 6],
      cost: {
        gold: 4000,
        wood: 10,
        ore: 5,
        gems: 10,
      },
      produces: {},
    },
    id46: {
      id: "id46",
      name: "Chthonic Home II",
      prev: ["id36"],
      next: null,
      pos: [4, 6],
      cost: {
        gold: 2500,
        wood: 15,
        ore: 10,
        gems: 10,
        dust: 75,
      },
      produces: {},
    },
    id17: {
      id: "id17",
      name: "Labyrinth",
      prev: ["id06"],
      next: ["id27", "id26", "id25"],
      pos: [1, 7],
      cost: {
        gold: 4000,
        wood: 5,
        ore: 10,
      },
      produces: {},
    },
    id27: {
      id: "id27",
      name: "Cave Place",
      prev: ["id17", "id18"],
      next: ["id27"],
      pos: [2, 7],
      cost: {
        gold: 17500,
        wood: 5,
        ore: 5,
        gems: 20,
      },
      produces: {},
    },
    id37: {
      id: "id37",
      name: "Cave Place II",
      prev: ["id27", "id28"],
      next: null,
      pos: [3, 7],
      cost: {
        gold: 22500,
        gems: 25,
        dust: 100,
      },
      produces: {},
    },
    id08: {
      id: "id08",
      name: "Mage Guild",
      prev: null,
      next: ["id18"],
      pos: [0, 8],
      cost: {
        gold: 2500,
        wood: 5,
      },
      produces: {},
    },
    id18: {
      id: "id18",
      name: "Mage Guild II",
      prev: ["id08"],
      next: ["id28"],
      pos: [1, 8],
      cost: {
        gold: 2500,
        gems: 2,
        crystals: 2,
        mercury: 2,
      },
      produces: {},
    },
    id28: {
      id: "id28",
      name: "Mage Guild III",
      prev: ["id18"],
      next: ["id38"],
      pos: [2, 8],
      cost: {
        gold: 2500,
        wood: 5,
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {},
    },
    id38: {
      id: "id38",
      name: "Mage Guild IV",
      prev: ["id28"],
      next: ["id48"],
      pos: [3, 8],
      cost: {
        gold: 2500,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id48: {
      id: "id48",
      name: "Mage Guild V",
      prev: ["id38"],
      next: null,
      pos: [4, 8],
      cost: {
        gold: 5000,
        wood: 10,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
  },
  temple: {
    id00: {
      id: "id00",
      name: "Golden Calf",
      prev: null,
      next: null,
      pos: [0, 0],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id10: {
      id: "id10",
      name: "Tavern",
      prev: null,
      next: ["id20"],
      pos: [1, 0],
      cost: {
        gold: 500,
        ore: 5,
      },
      produces: {},
    },
    id20: {
      id: "id20",
      name: "Marketplace",
      prev: ["id10"],
      next: ["id31", "id30"],
      pos: [2, 0],
      cost: {
        gold: 500,
        wood: 5,
      },
      produces: {},
    },
    id30: {
      id: "id30",
      name: "Artifact Merchant",
      prev: ["id20"],
      next: null,
      pos: [3, 0],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id01: {
      id: "id01",
      name: "Solar Temple",
      prev: null,
      next: ["id11"],
      pos: [0, 1],
      cost: {
        gold: 0,
      },
      produces: {
        gold: 500,
        law: 500,
        astrology: 500,
      },
    },
    id11: {
      id: "id11",
      name: "Solar Temple II",
      prev: ["id01"],
      next: ["id21", "id22"],
      pos: [1, 1],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id21: {
      id: "id21",
      name: "Solar Temple III",
      prev: ["id11"],
      next: null,
      pos: [2, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id31: {
      id: "id31",
      name: "Resource Depot",
      prev: ["id20", "id22"],
      next: ["id41"],
      pos: [3, 1],
      cost: {
        gold: 2000,
      },
      produces: {
        gems: 1,
      },
    },
    id41: {
      id: "id41",
      name: "Alchemic Depot",
      prev: ["id31"],
      next: null,
      pos: [4, 1],
      cost: {
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {
        dust: 5,
      },
    },
    id12: {
      id: "id12",
      name: "Guild of Six Winds",
      prev: null,
      next: null,
      pos: [1, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
        crystals: 2,
        gems: 2,
        mercury: 2,
      },
      produces: {},
    },
    id22: {
      id: "id22",
      name: "Bank",
      prev: ["id11"],
      next: ["id31", "id32"],
      pos: [2, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 1000,
      },
    },
    id32: {
      id: "id32",
      name: "Treasury",
      prev: ["id22", "id23"],
      next: null,
      pos: [3, 2],
      cost: {
        gold: 5000,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {
        gold: 2000,
      },
    },
    id13: {
      id: "id13",
      name: "Scouting Skyship",
      prev: null,
      next: null,
      pos: [1, 3],
      cost: {
        gold: 2500,
      },
      produces: {},
    },
    id23: {
      id: "id23",
      name: "Fortifications",
      prev: null,
      next: ["id33"],
      pos: [2, 3],
      cost: {
        gold: 2500,
        ore: 5,
      },
      produces: {},
    },
    id33: {
      id: "id33",
      name: "Fortifications II",
      prev: ["id23"],
      next: ["id43", "id42"],
      pos: [3, 3],
      cost: {
        gold: 2500,
        ore: 10,
      },
      produces: {},
    },
    id43: {
      id: "id43",
      name: "Fortifications III",
      prev: ["id33"],
      next: null,
      pos: [4, 3],
      cost: {
        gold: 5000,
        ore: 15,
      },
      produces: {},
    },
    id24: {
      id: "id24",
      name: "Garrison II",
      prev: ["id15"],
      next: null,
      pos: [2, 4],
      cost: {
        gold: 1000,
        ore: 5,
        dust: 10,
      },
      produces: {},
    },
    id34: {
      id: "id34",
      name: "Hippodrome II",
      prev: ["id25"],
      next: null,
      pos: [3, 4],
      cost: {
        gold: 4500,
        wood: 20,
        ore: 5,
        dust: 50,
      },
      produces: {},
    },
    id15: {
      id: "id15",
      name: "Garrison",
      prev: null,
      next: ["id24"],
      pos: [1, 5],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id25: {
      id: "id25",
      name: "Hippodrome",
      prev: ["id15", "id16"],
      next: ["id34"],
      pos: [2, 5],
      cost: {
        gold: 6000,
        wood: 15,
      },
      produces: {},
    },
    id35: {
      id: "id35",
      name: "Threshold Basilica",
      prev: ["id26"],
      next: ["id45"],
      pos: [3, 5],
      cost: {
        gold: 3500,
        ore: 10,
        gems: 10,
      },
      produces: {},
    },
    id45: {
      id: "id45",
      name: "Threshold Basilica II",
      prev: ["id35"],
      next: null,
      pos: [4, 5],
      cost: {
        gold: 2000,
        ore: 10,
        gems: 15,
        dust: 75,
      },
      produces: {},
    },
    id06: {
      id: "id06",
      name: "Mews",
      prev: null,
      next: ["id16", "id17"],
      pos: [0, 6],
      cost: {
        gold: 2250,
        wood: 5,
      },
      produces: {},
    },
    id16: {
      id: "id16",
      name: "Griffin Rookery",
      prev: ["id06"],
      next: ["id26", "id27", "id25"],
      pos: [1, 6],
      cost: {
        gold: 3250,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id26: {
      id: "id26",
      name: "Sundrop Chapel",
      prev: ["id16"],
      next: ["id36", "id37", "id35"],
      pos: [2, 6],
      cost: {
        gold: 3250,
        gems: 3,
        mercury: 3,
        crystals: 3,
      },
      produces: {},
    },
    id36: {
      id: "id36",
      name: "Sundrop Chapel II",
      prev: ["id26"],
      next: null,
      pos: [3, 6],
      cost: {
        gold: 3250,
        gems: 6,
        dust: 40,
      },
      produces: {},
    },
    id17: {
      id: "id17",
      name: "Mews II",
      prev: ["id06"],
      next: null,
      pos: [1, 7],
      cost: {
        gold: 1500,
        wood: 5,
        dust: 20,
      },
      produces: {},
    },
    id27: {
      id: "id27",
      name: "Griffin Rookery II",
      prev: ["id16"],
      next: null,
      pos: [2, 7],
      cost: {
        gold: 2250,
        wood: 5,
        ore: 5,
        dust: 30,
      },
      produces: {},
    },
    id37: {
      id: "id37",
      name: "Radiant Forge",
      prev: ["id26", "id28"],
      next: ["id47"],
      pos: [3, 7],
      cost: {
        gold: 15000,
        gems: 10,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
    id47: {
      id: "id47",
      name: "Radiant Forge II",
      prev: ["id37"],
      next: null,
      pos: [4, 7],
      cost: {
        gold: 17500,
        gems: 20,
        dust: 100,
      },
      produces: {},
    },
    id18: {
      id: "id18",
      name: "Mage Guild",
      prev: null,
      next: ["id28"],
      pos: [1, 8],
      cost: {
        gold: 2500,
        wood: 5,
      },
      produces: {},
    },
    id28: {
      id: "id28",
      name: "Mage Guild II",
      prev: ["id18"],
      next: ["id38"],
      pos: [2, 8],
      cost: {
        gold: 2500,
        gems: 2,
        crystals: 2,
        mercury: 2,
      },
      produces: {},
    },
    id38: {
      id: "id38",
      name: "Mage Guild III",
      prev: ["id28"],
      next: ["id48"],
      pos: [3, 8],
      cost: {
        gold: 2500,
        wood: 5,
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {},
    },
    id48: {
      id: "id48",
      name: "Mage Guild IV",
      prev: ["id38"],
      next: ["id58"],
      pos: [4, 8],
      cost: {
        gold: 2500,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
  },
  schism: {
    id00: {
      id: "id00",
      name: "Firmament's Abyss",
      prev: null,
      next: null,
      pos: [0, 0],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id10: {
      id: "id10",
      name: "Tavern",
      prev: null,
      next: ["id20"],
      pos: [1, 0],
      cost: {
        gold: 500,
        ore: 5,
      },
      produces: {},
    },
    id20: {
      id: "id20",
      name: "Marketplace",
      prev: ["id10"],
      next: ["id31", "id30"],
      pos: [2, 0],
      cost: {
        gold: 500,
        wood: 5,
      },
      produces: {},
    },
    id30: {
      id: "id30",
      name: "Artifact Merchant",
      prev: ["id20"],
      next: null,
      pos: [3, 0],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id01: {
      id: "id01",
      name: "Abyssal Remnant",
      prev: null,
      next: ["id11"],
      pos: [0, 1],
      cost: {
        gold: 0,
      },
      produces: {
        gold: 500,
        law: 500,
        astrology: 500,
      },
    },
    id11: {
      id: "id11",
      name: "Abyssal Remnant II",
      prev: ["id01"],
      next: ["id21", "id22"],
      pos: [1, 1],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id21: {
      id: "id21",
      name: "Abyssal Remnant III",
      prev: ["id11"],
      next: null,
      pos: [2, 1],
      cost: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      produces: {
        gold: 250,
        law: 250,
        astrology: 250,
      },
    },
    id31: {
      id: "id31",
      name: "Resource Depot",
      prev: ["id20", "id22"],
      next: ["id41"],
      pos: [3, 1],
      cost: {
        gold: 2000,
      },
      produces: {
        gems: 1,
      },
    },
    id41: {
      id: "id41",
      name: "Alchemic Depot",
      prev: ["id31"],
      next: null,
      pos: [4, 1],
      cost: {
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {
        dust: 5,
      },
    },
    id02: {
      id: "id02",
      name: "Great Library",
      prev: null,
      next: null,
      pos: [0, 2],
      cost: {
        gold: 5000,
      },
      produces: {},
    },
    id22: {
      id: "id22",
      name: "Bank",
      prev: ["id11"],
      next: ["id31", "id32"],
      pos: [2, 2],
      cost: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      produces: {
        gold: 1000,
      },
    },
    id32: {
      id: "id32",
      name: "Treasury",
      prev: ["id22", "id23"],
      next: null,
      pos: [3, 2],
      cost: {
        gold: 5000,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {
        gold: 2000,
      },
    },
    id23: {
      id: "id23",
      name: "Fortifications",
      prev: null,
      next: ["id33"],
      pos: [2, 3],
      cost: {
        gold: 2500,
        ore: 5,
      },
      produces: {},
    },
    id33: {
      id: "id33",
      name: "Fortifications II",
      prev: ["id23"],
      next: ["id43", "id42"],
      pos: [3, 3],
      cost: {
        gold: 2500,
        ore: 10,
      },
      produces: {},
    },
    id43: {
      id: "id43",
      name: "Fortifications III",
      prev: ["id33"],
      next: null,
      pos: [4, 3],
      cost: {
        gold: 5000,
        ore: 15,
      },
      produces: {},
    },
    id04: {
      id: "id04",
      name: "Cultist Spire",
      prev: null,
      next: ["id14", "id15"],
      pos: [0, 4],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id14: {
      id: "id14",
      name: "Cultist Spire II",
      prev: ["id04"],
      next: null,
      pos: [1, 4],
      cost: {
        gold: 2000,
        wood: 5,
        ore: 5,
        dust: 20,
      },
      produces: {},
    },
    id24: {
      id: "id24",
      name: "House of Chains",
      prev: ["id15"],
      next: ["id34", "id35"],
      pos: [2, 4],
      cost: {
        gold: 4750,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id34: {
      id: "id34",
      name: "House of Chains II",
      prev: ["id24"],
      next: null,
      pos: [3, 4],
      cost: {
        gold: 1500,
        wood: 15,
        ore: 15,
        dust: 50,
      },
      produces: {},
    },
    id15: {
      id: "id15",
      name: "Aga'Shoth Stables",
      prev: ["id04"],
      next: ["id25", "id24", "id26"],
      pos: [1, 5],
      cost: {
        gold: 2750,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id25: {
      id: "id25",
      name: "Aga'Shoth Stables II",
      prev: ["id15"],
      next: null,
      pos: [2, 5],
      cost: {
        gold: 750,
        wood: 10,
        ore: 10,
        dust: 30,
      },
      produces: {},
    },
    id35: {
      id: "id35",
      name: "Bloated Mansion",
      prev: ["id24"],
      next: ["id45"],
      pos: [3, 5],
      cost: {
        gold: 7750,
        wood: 5,
        ore: 5,
      },
      produces: {},
    },
    id45: {
      id: "id45",
      name: "Bloated Mansion II",
      prev: ["id35"],
      next: null,
      pos: [4, 5],
      cost: {
        gold: 3750,
        wood: 20,
        ore: 20,
        dust: 75,
      },
      produces: {},
    },
    id06: {
      id: "id06",
      name: "Lesser Summoning Rite",
      prev: null,
      next: ["id16", "id17"],
      pos: [0, 6],
      cost: {
        gold: 0,
      },
      produces: {},
    },
    id16: {
      id: "id16",
      name: "Lesser Summoning Rite II",
      prev: ["id06"],
      next: null,
      pos: [1, 6],
      cost: {
        gold: 250,
        mercury: 5,
        dust: 10,
      },
      produces: {},
    },
    id26: {
      id: "id26",
      name: "Eerie Summoning Rite",
      prev: ["id15", "id17"],
      next: ["id36"],
      pos: [2, 6],
      cost: {
        gold: 12500,
        mercury: 20,
        gems: 5,
        crystals: 5,
      },
      produces: {},
    },
    id36: {
      id: "id36",
      name: "Eerie Summoning Rite II",
      prev: ["id26"],
      next: null,
      pos: [3, 6],
      cost: {
        gold: 17500,
        mercury: 25,
        dust: 100,
      },
      produces: {},
    },
    id07: {
      id: "id07",
      name: "Involuntary Summons",
      prev: null,
      next: null,
      pos: [0, 7],
      cost: {
        gold: 5000,
        mercury: 3,
        gems: 3,
        crystals: 3,
      },
      produces: {},
    },
    id17: {
      id: "id17",
      name: "Disturbing Summoning Rite",
      prev: ["id06", "id08"],
      next: ["id27", "id26"],
      pos: [1, 7],
      cost: {
        gold: 2250,
        mercury: 6,
        gems: 3,
        crystals: 3,
      },
      produces: {},
    },
    id27: {
      id: "id27",
      name: "Disturbing Summoning Rite II",
      prev: ["id17"],
      next: null,
      pos: [2, 7],
      cost: {
        gold: 2000,
        mercury: 10,
        dust: 40,
      },
      produces: {},
    },

    id08: {
      id: "id08",
      name: "Mage Guild",
      prev: null,
      next: ["id18"],
      pos: [0, 8],
      cost: {
        gold: 2500,
        wood: 5,
      },
      produces: {},
    },
    id18: {
      id: "id18",
      name: "Mage Guild II",
      prev: ["id08"],
      next: ["id28"],
      pos: [1, 8],
      cost: {
        gold: 2500,
        gems: 2,
        crystals: 2,
        mercury: 2,
      },
      produces: {},
    },
    id28: {
      id: "id28",
      name: "Mage Guild III",
      prev: ["id18"],
      next: ["id38"],
      pos: [2, 8],
      cost: {
        gold: 2500,
        wood: 5,
        gems: 3,
        crystals: 3,
        mercury: 3,
      },
      produces: {},
    },
    id38: {
      id: "id38",
      name: "Mage Guild IV",
      prev: ["id28"],
      next: ["id48"],
      pos: [3, 8],
      cost: {
        gold: 2500,
        gems: 5,
        crystals: 5,
        mercury: 5,
      },
      produces: {},
    },
  },
} as const;

export const initCastlePreBuilds = {
  hive: ["id10", "id01", "id05", "id06"],
  necropolis: ["id10", "id01", "id05", "id07"],
  grove: ["id10", "id01", "id05"],
  dungeon: ["id10", "id01", "id04", "id06"],
  temple: ["id10", "id01", "id15", "id06"],
  schism: ["id10", "id01", "id04", "id06"],
} as const;

export const secondaryCastlePreBuilds = {
  hive: ["id10", "id01", "id06"],
  necropolis: ["id10", "id01", "id05"],
  grove: ["id10", "id01", "id05"],
  dungeon: ["id10", "id01", "id04"],
  temple: ["id10", "id01", "id15"],
  schism: ["id10", "id01", "id06"],
} as const;
