import { writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const lawConfigPath = join(__dirname, "../../law/src/features/laws/laws.config.ts");
const outFile = join(__dirname, "../src/routes/faction/law.seo.ts");

if (!existsSync(lawConfigPath)) {
  console.log("Law MFE not found — using committed law.seo.ts");
  process.exit(0);
}

const { LAWS } = await import(lawConfigPath);

const factions = ["hive", "necropolis", "grove", "dungeon", "temple", "schism"];

const result = {};
for (const faction of factions) {
  const laws = LAWS[faction];
  result[faction] = Object.values(laws)
    .filter((entry) => entry.title !== undefined)
    .map((entry) => ({
      title: entry.title,
      description: entry.description({ lvl: entry.max, sight: 3 }),
    }));
}

writeFileSync(
  outFile,
  `// Auto-generated by scripts/gen-law-seo.mjs — do not edit\nexport const lawSeo = ${JSON.stringify(result, null, 2)} as const;\n`
);

const total = Object.values(result).reduce((s, arr) => s + arr.length, 0);
console.log(`Generated law.seo.ts — ${total} laws across ${factions.length} factions`);
