/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroIdRouteImport } from './routes/hero/$id'
import { Route as CastleIdRouteImport } from './routes/castle/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroIdRoute = HeroIdRouteImport.update({
  id: '/hero/$id',
  path: '/hero/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CastleIdRoute = CastleIdRouteImport.update({
  id: '/castle/$id',
  path: '/castle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/castle/$id': typeof CastleIdRoute
  '/hero/$id': typeof HeroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/castle/$id': typeof CastleIdRoute
  '/hero/$id': typeof HeroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/castle/$id': typeof CastleIdRoute
  '/hero/$id': typeof HeroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/castle/$id' | '/hero/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/castle/$id' | '/hero/$id'
  id: '__root__' | '/' | '/castle/$id' | '/hero/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CastleIdRoute: typeof CastleIdRoute
  HeroIdRoute: typeof HeroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/$id': {
      id: '/hero/$id'
      path: '/hero/$id'
      fullPath: '/hero/$id'
      preLoaderRoute: typeof HeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castle/$id': {
      id: '/castle/$id'
      path: '/castle/$id'
      fullPath: '/castle/$id'
      preLoaderRoute: typeof CastleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CastleIdRoute: CastleIdRoute,
  HeroIdRoute: HeroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
